name: auction
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.0
  go_router: ^14.2.7
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  cloud_functions: ^5.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  cupertino_icons: ^1.0.8

  #provider
  provider: ^6.1.2

  #swipe
  flutter_swiper_null_safety: ^1.0.2
  firebase_storage: ^12.3.2
  permission_handler: ^11.3.1

  #splashscreen:
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/stockAuction_appIcon.png"
  adaptive_icon_background: "#c0b6ae"
  adaptive_icon_foreground: "lib/assets/icon/stockAuction_appIcon.png"
  
flutter:

  uses-material-design: true

  assets:
    - lib/assets/image/pic1.png
    - lib/assets/image/pic2.png
    - lib/assets/image/pic3.png
    - lib/assets/image/defaultUserProfile.png
    - lib/assets/image/loginimage.png
    - lib/assets/image/default_profile/default_blue.png
    - lib/assets/image/default_profile/default_green.png
    - lib/assets/image/default_profile/default_mint.png
    - lib/assets/image/default_profile/default_red.png
    - lib/assets/image/default_profile/default_yellow.png
    - lib/assets/icon/stockAuction_appIcon.png
